import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>HuskyCoin Dapp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to the <a href="https://polygonscan.com/">HuskyCoin</a> Dapp!
        </h1>

        <p className={styles.description}>
          An Interactive Introductory Tutorial to Web3 on Ethereum
        </p>
        <p>Get started below:</p>

        <div className={styles.grid}>
          <a href="https://metamask.io" className={styles.card}>
            <h2>Setting up MetaMask &rarr;</h2>
            <p>A crypto wallet is your gateway to Web3 infrastructure. Other crypto wallet options include Coinbase Wallet and Brave Wallet.</p>
          </a>

          <a href="https://info.etherscan.com/what-is-an-ethereum-address/" className={styles.card}>
            <h2>Generate an Ethereum address &rarr;</h2>
            <p>Learn about the insane things an Ethereum address is capable of and explore Etherscan, where all of Web3 is publically visible.</p>
          </a>
          
          <Link href="/faucet">
          <a
            className={styles.card}
          >
            <h2>HuskyCoin Faucet &rarr;</h2>
            <p>Claim your first 69420 ERC20 tokens from the HuskyCoin faucet.</p>
          </a>
          </Link>

          <Link href="/stake">
          <a
            className={styles.card}
          >
            <h2>Stake HuskyCoins &rarr;</h2>
            <p>
              Grow your token balance by staking HuskyCoins and earning passive income!
            </p>
          </a>
          </Link>
        </div>
      </main>

      <footer className={styles.footer}>
      </footer>
    </div>
  )
}
